### ISSUE TITLE
Error on TS

### ISSUE THREAD

**Issue by gfratmct** [andreafdaf/node-fatture-in-cloud-api#3]
I tried to get my clients list but with typescript but not work...

This is the error:
`error: TypeError: fatture_in_cloud_api_1.default is not a constructor`

The code:

```
listCustomers: async (_req: express.Request, res: ResponseUser, _next: express.NextFunction) => {
  const fic = new FattureInCloudApi();
  const result = await fic.clienti.lista();
  res.status(200).send(result);
}
```
I've imported the module like this: `import FattureInCloudApi from 'fatture-in-cloud-api';`

**Comment by andreafdaf** [comment]
Hi @xjabr, sorry for this late reply!

This module is written in TypeScript but it is meant to be a NodeJS module so it is exported as:
```ts
export = class FattureInCloudAPI ...
```

If you want to use it in a TypeScript project you need to import it like:
```ts
import FattureInCloudAPI = require('fatture-in-cloud-api')
```

I'll find a way to make it interoperable on both TypeScript and NodeJS, but for now it must be imported like this

**Comment by andreafdaf** [comment]
Hi @xjabr!

Is your problem solved? Can we close the issue?

**Comment by gfratmct** [comment]
HI @andreafdaf, Yes, I solved the problem, thank you.
